---
- name: Run Podman must-gather-singleton
  hosts: localhost
  become: yes
  vars:
    # Define your containers with their unique properties
    containers:
      - name: must-gather-singleton-1
        image: quay.io/midu/must-gather-singleton:latest
        kubeconfig_volume_src: /root/.kcli/spoke-1/hub/auth/kubeconfig
        kubeconfig_container_dest: /apps/root/.kube/config
        volume_src: /tmp/apps/must_gather_singleton/spoke-1/
        container_dest: /apps/must-gather/

      - name: must-gather-singleton-2
        image: quay.io/midu/must-gather-singleton:latest
        kubeconfig_volume_src: /root/.kcli/spoke-1/hub/auth/kubeconfig
        kubeconfig_container_dest: /apps/root/.kube/config
        volume_src: /apps/must-gather-singleton/spoke-2/
        container_dest: /apps/must-gather/

      # Add more container configurations as needed
  tasks:
    - name: Ensure podman is installed
      package:
        name: podman
        state: present
    - name: Start Podman must-gather-singleton container(s)
      containers.podman.podman_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        volumes:
          - "{{ item.kubeconfig_volume_src }}:{{ item.kubeconfig_container_dest }}"
          - "{{ item.volume_src }}:{{ item.container_dest }}"
        env:
          KUBECONFIG: "/apps/must-gather/kubeconfig"
          DEBUG: ""
      loop: "{{ containers }}"
      loop_control:
        loop_var: item

