name: container-base-image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v4
    - name: Set up environment variables
      run: echo "IMAGE_TAG=must-gather-singleton:$(date +%s)" >> $GITHUB_ENV
    - name: Build the container-base-image
      run: podman build . --file Containerfile --tag ${{ env.IMAGE_TAG }}
    - name: Tag the container-base-image
      run: podman tag ${{ env.IMAGE_TAG }} quay.io/midu/${{ env.IMAGE_TAG }}
    - name: List the images
      run: podman images
    - name: Push the container-base-image to quay.io
      run: podman push quay.io/midu/${{ env.IMAGE_TAG }}
