name: container-base-image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v4
    - name: Build the container-base-image
      run: podman build . --file Containerfile --tag must-gather-singleton:$(date +%s)
    - name: Tag the container-base-image
      run: podman tag must-gather-singleton:$(date +%s) quay.io/midu/must-gather-singleton:$(date +%s)
    - name: List the images
      run: podman images 
