name: container-base-image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux, x64]

    env:
      IMAGE_NAME: must-gather-singleton:$(date +%s)
    steps:
    - uses: actions/checkout@v4
    - name: Build the container-base-image
      run: podman build . --file Containerfile --tag ${{IMAGE_TAG}}
    - name: Tag the container-base-image
      run: podman tag ${{IMAGE_TAG}} quay.io/midu/${{IMAGE_TAG}}
    - name: List the images
      run: podman images 
